name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Copy env files from config folder
      run: cp -rf /var/www/config/* /var/www/config/.* /var/www/yemsay-server/_work/yemsay/yemsay

    - name: Install dependencies
      run: npm install

    - name: Reload server instances
      run: pm2 reload yemsay-server --update-env --wait-ready